Repository Coding-in-community/exercicios-CeV, pull requests merged in 2021-01, with the labels that each got.

#3 hello, world
  exs/mundo_1/java/001.java
  exs/mundo_1/java/002.java
Labels: enhancement

#10 Organizing
  LICENSE
  exs/mundo_1/readme.md
  exs/mundo_2/readme.md
  exs/mundo_3/readme.md
Labels: Improve

#15 Add Contribution Guide
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement

#17 adding comments to c++ problems
  exs/mundo_1/c++/001.cpp
  exs/mundo_1/c++/002.cpp
  exs/mundo_1/c++/003.cpp
  exs/mundo_1/c++/005.cpp
  exs/mundo_1/c++/006.cpp
  exs/mundo_1/c++/007.cpp
  exs/mundo_1/c++/008.cpp
  exs/mundo_1/c++/009.cpp
  exs/mundo_1/c++/010.cpp
  exs/mundo_1/c++/011.cpp
  exs/mundo_1/c++/012.cpp
  exs/mundo_1/c++/013.cpp
  exs/mundo_1/c++/014.cpp
  exs/mundo_1/c++/015.cpp
  exs/mundo_1/c++/016.cpp
  exs/mundo_1/c++/017.cpp
Labels: documentation

#20 Adicionando novos desafios GoLang
  exs/mundo_1/golang/001.go
  exs/mundo_1/golang/002.go
  exs/mundo_1/golang/003.go
Labels: New solutions

#18 adding more javascript problems
  exs/mundo_1/javascript/001.js
  exs/mundo_1/javascript/002.js
  exs/mundo_1/javascript/003.js
  exs/mundo_1/javascript/004.js
  exs/mundo_1/javascript/021.html
  exs/mundo_1/javascript/022.js
  exs/mundo_1/javascript/023.js
  exs/mundo_1/javascript/024.js
  exs/mundo_1/javascript/025.js
  exs/mundo_1/javascript/026.js
  exs/mundo_1/javascript/027.js
  exs/mundo_1/javascript/028.js
  exs/mundo_1/javascript/029.js
  exs/mundo_1/javascript/030.js
  exs/mundo_1/javascript/031.js
  exs/mundo_1/javascript/032.js
  exs/mundo_1/javascript/033.js
  exs/mundo_1/javascript/034.js
  exs/mundo_1/javascript/035.js
  exs/mundo_1/readme.md
Labels: New solutions, enhancement

#19 exercícios resolvidos em ruby 2.7
  exs/mundo_1/ruby/001.rb
  exs/mundo_1/ruby/002.rb
  exs/mundo_1/ruby/003.rb
  exs/mundo_1/ruby/005.rb
  exs/mundo_1/ruby/006.rb
  exs/mundo_1/ruby/007.rb
  exs/mundo_1/ruby/008.rb
  exs/mundo_1/ruby/009.rb
  exs/mundo_1/ruby/010.rb
  exs/mundo_1/ruby/011.rb
  exs/mundo_1/ruby/012.rb
  exs/mundo_1/ruby/013.rb
  exs/mundo_1/ruby/014.rb
  exs/mundo_1/ruby/015.rb
  exs/mundo_1/ruby/016.rb
  exs/mundo_1/ruby/017.rb
  exs/mundo_1/ruby/018.rb
  exs/mundo_1/ruby/019.rb
  exs/mundo_1/ruby/020.rb
Labels: New solutions

#22 [FIX] Arrumado bugs no ex004 de javascript
  exs/mundo_1/javascript/004.js
Labels: Improve

#24 ex 012, 013, 014 and 015
  exs/mundo_1/java/012.java
  exs/mundo_1/java/013.java
  exs/mundo_1/java/014.java
  exs/mundo_1/java/015.java
Labels: New solutions

#21 Adicionando mais exercicios de Ruby
  exs/mundo_1/ruby/004.rb
  exs/mundo_1/ruby/021.rb
  exs/mundo_1/ruby/022.rb
  exs/mundo_1/ruby/023.rb
  exs/mundo_1/ruby/024.rb
  exs/mundo_1/ruby/025.rb
  exs/mundo_1/ruby/026.rb
  exs/mundo_1/ruby/027.rb
  exs/mundo_1/ruby/028.rb
  exs/mundo_1/ruby/029.rb
  exs/mundo_1/ruby/030.rb
  exs/mundo_1/ruby/031.rb
  exs/mundo_1/ruby/032.rb
  exs/mundo_1/ruby/033.rb
  exs/mundo_1/ruby/034.rb
  exs/mundo_1/ruby/035.rb
Labels: New solutions

#23 Adding problems description only
  README.md
  exs/mundo_1/enunciados.md
  exs/mundo_2/enunciados.md
  exs/mundo_3/enunciados.md
Labels: documentation, enhancement

#25 Melhorando a documentação do README
  .github/assets/images/coding_in_community.png
  .github/assets/images/curso_em_video.png
  README.md
Labels: Improve, documentation, enhancement

#32 [FEAT] adicionado novos exercicios de javascript
  exs/mundo_1/javascript/005.js
  exs/mundo_1/javascript/006.js
  exs/mundo_1/javascript/007.js
  exs/mundo_1/javascript/008.js
  exs/mundo_1/javascript/009.js
  exs/mundo_1/javascript/010.js
Labels: New solutions

#30 Adicionando novos desafios GoLang
  exs/mundo_1/golang/005.go
  exs/mundo_1/golang/006.go
  exs/mundo_1/golang/007.go
  exs/mundo_1/golang/008.go
  exs/mundo_1/golang/009.go
  exs/mundo_1/golang/010.go
Labels: New solutions

#34 Diretório para assets dos exercícios no Mundo 1
  exs/mundo_1/assets/audio/021.mp3
  exs/mundo_1/javascript/021.html
  exs/mundo_1/python/021.py
  exs/mundo_1/ruby/021.rb
Labels: Improve, bug, enhancement

#35 Feature/ruby
  exs/mundo_1/ruby/004.rb
  exs/mundo_1/ruby/010.rb
  exs/mundo_1/ruby/025.rb
  exs/mundo_2/ruby/036.rb
  exs/mundo_2/ruby/037.rb
  exs/mundo_2/ruby/038.rb
  exs/mundo_2/ruby/039.rb
  exs/mundo_2/ruby/040.rb
  exs/mundo_2/ruby/041.rb
Labels: New solutions

#36 Feature/go lang
  exs/mundo_1/golang/004.go
  exs/mundo_2/ruby/041.rb
Labels: New solutions

#37 [FIX] Corrigindo erros de logica.
  exs/mundo_1/ruby/012.rb
Labels: bug

#38 Feature/go lang
  exs/mundo_1/golang/011.go
  exs/mundo_1/golang/012.go
  exs/mundo_1/ruby/021.rb
Labels: New solutions

#39 Alterar nome da branch main para master
  CONTRIBUTING.md
Labels: documentation

#40 Novos exercicios em Ruby 2.7
  exs/mundo_2/ruby/042.rb
  exs/mundo_2/ruby/043.rb
  exs/mundo_2/ruby/044.rb
  exs/mundo_2/ruby/045.rb
  exs/mundo_2/ruby/046.rb
  exs/mundo_2/ruby/047.rb
  exs/mundo_2/ruby/048.rb
  exs/mundo_2/ruby/049.rb
  exs/mundo_2/ruby/050.rb
Labels: New solutions, needs changes

#42 Novos exercicios em ruby 2.7
  exs/mundo_2/readme.md
  exs/mundo_2/ruby/051.rb
  exs/mundo_2/ruby/052.rb
  exs/mundo_2/ruby/053.rb
  exs/mundo_2/ruby/054.rb
  exs/mundo_2/ruby/055.rb
Labels: documentation, new solutions

#43 Corrigindo alguns erros.
  exs/mundo_2/readme.md
  exs/mundo_2/ruby/054.rb
  exs/mundo_2/ruby/056.rb
Labels: new solutions

#44 Corrigindo alguns erros.
  exs/mundo_2/ruby/055.rb
Labels: new solutions

#45 Exercicios 57 a 60 em Ruby 2.7.
  exs/mundo_2/readme.md
  exs/mundo_2/ruby/051.rb
  exs/mundo_2/ruby/057.rb
  exs/mundo_2/ruby/058.rb
  exs/mundo_2/ruby/059.rb
  exs/mundo_2/ruby/060.rb
  exs/mundo_2/ruby/061.rb
  exs/mundo_2/ruby/062.rb
  exs/mundo_2/ruby/063.rb
  exs/mundo_2/ruby/064.rb
  exs/mundo_2/ruby/065.rb
  exs/mundo_2/ruby/066.rb
  exs/mundo_2/ruby/067.rb
  exs/mundo_2/ruby/068.rb
  exs/mundo_2/ruby/069.rb
  exs/mundo_2/ruby/070.rb
  exs/mundo_2/ruby/071.rb
Labels: new solutions

#48 [FEAT] adicionado exercicios de c#
  exs/mundo_1/c#/011.cs
  exs/mundo_1/c#/012.cs
  exs/mundo_1/c#/013.cs
  exs/mundo_1/c#/014.cs
  exs/mundo_1/c#/015.cs
  exs/mundo_1/c#/016.cs
  exs/mundo_1/c#/017.cs
  exs/mundo_1/c#/018.cs
  exs/mundo_1/c#/019.cs
  exs/mundo_1/c#/020.cs
Labels: new solutions

#49 Ajustes em todos os readme's de índices dos exercícios
  exs/mundo_1/readme.md
  exs/mundo_2/readme.md
  exs/mundo_3/readme.md
Labels: Improve, documentation

#51 ex c#
  exs/mundo_1/c#/021.cs
  exs/mundo_1/c#/022.cs
  exs/mundo_1/c#/023.cs
  exs/mundo_1/c#/024.cs
  exs/mundo_1/c#/025.cs
  exs/mundo_1/c#/026.cs
  exs/mundo_1/c#/027.cs
  exs/mundo_1/c#/028.cs
  exs/mundo_1/c#/029.cs
  exs/mundo_1/c#/030.cs
Labels: needs changes, new solutions

#53 Corrigir nomenclatura da base de conversão
  exs/mundo_2/python/037.py
Labels: Improve

#55 Exercicioscev/csharp
  .gitignore
  exs/mundo_1/c#/031.cs
  exs/mundo_1/c#/032.cs
  exs/mundo_1/c#/033.cs
  exs/mundo_1/c#/034.cs
  exs/mundo_1/c#/035.cs
Labels: needs changes, new solutions

#56 Go
  exs/mundo_1/golang/019.go
  exs/mundo_1/golang/020.go
  exs/mundo_1/golang/021.go
  exs/mundo_1/golang/022.go
  exs/mundo_1/golang/023.go
  exs/mundo_1/golang/024.go
  exs/mundo_1/golang/025.go
  exs/mundo_1/readme.md
Labels: documentation, needs changes, new solutions

#58 [FEAT] Adiciona os exercícios do mundo 1 na linguagem C
  exs/mundo_1/c/001.c
  exs/mundo_1/c/002.c
  exs/mundo_1/c/003.c
  exs/mundo_1/c/005.c
  exs/mundo_1/c/006.c
  exs/mundo_1/c/007.c
  exs/mundo_1/c/008.c
  exs/mundo_1/c/009.c
  exs/mundo_1/c/010.c
  exs/mundo_1/c/011.c
  exs/mundo_1/c/012.c
  exs/mundo_1/c/013.c
  exs/mundo_1/c/014.c
  exs/mundo_1/c/015.c
  exs/mundo_1/c/016.c
  exs/mundo_1/c/017.c
Labels: new solutions

#59 Corrigir erro de digitação no ex 031
  exs/mundo_1/javascript/031.js
  exs/mundo_1/python/031.py
  exs/mundo_1/ruby/031.rb
Labels: Improve, documentation

#57 Exercicioscev/java
  exs/mundo_1/java/022.java
  exs/mundo_1/java/023.java
  exs/mundo_1/java/024.java
  exs/mundo_1/java/025.java
  exs/mundo_1/java/026.java
  exs/mundo_1/java/027.java
  exs/mundo_1/java/028.java
  exs/mundo_1/java/029.java
  exs/mundo_1/java/030.java
  exs/mundo_1/java/031.java
  exs/mundo_1/java/032.java
  exs/mundo_1/java/033.java
  exs/mundo_1/java/034.java
  exs/mundo_1/java/035.java
Labels: needs changes, new solutions

#60 [DOCS] Atualiza o mundo_1/readme.md
  exs/mundo_1/readme.md
Labels: documentation
